### ISSUE TITLE
Objects are not valid as a React child.

### ISSUE THREAD

**Issue by AjayDhimanELS** [sshyam-gupta/react-datamaps-india#20]
Got the following in the console while trying the following in my `App.js`:
 `Objects are not valid as a React child (found: object with keys {name}). If you meant to render a collection of children, use an array instead.`
Can you please help with it?

**Comment by sshyam-gupta** [comment]
@AjayDhimanELS can you please share small snippet of your code?

**Comment by iravikds** [comment]
> 
> 
> Got the following in the console while trying the following in my `App.js`:
> `Objects are not valid as a React child (found: object with keys {name}). If you meant to render a collection of children, use an array instead.`
> Can you please help with it?

Same problem.

**Comment by AjayDhimanELS** [comment]
Sorry about my late reply, @sshyam-gupta - I tried everything as mentioned [here](https://github.com/sshyam-gupta/react-datamaps-india#usage).  And as @iravikds is also facing the same issue. Can you please review your code and see if it actually works for you?.
Thanks.

**Comment by sshyam-gupta** [comment]
Sorry @iravikds @AjayDhimanELS ,
I think the issue is with the README file.

can u try
```
hoverComponent={({ value }) => {
  return <span>{value.name}{value.value}</span>}}

```
instead of 

```
hoverComponent={({ value }) => {
  return <span>{value}</span>
}}
```


I will update README soon.

**Comment by AjayDhimanELS** [comment]
Thanks.
